# Generated by Django 5.1.1 on 2024-09-18 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodentry',
            name='feelings',
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='mood_intensity',
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='time',
        ),
    ]
